[General]
# Look
background=Assets/Wallpaper/mothline.png
fontFamily="JetBrainsMono Nerd Font Mono"
colorScheme="Mothline"
darkMode=true
hideShadow=false
# Style
clockStyle="digital"
# Scaling
fontScale=1.0
radiusRatio=0.55
iRadiusRatio=0.55
screenRadiusRatio=1.0
scaleRatio=1.0
animationSpeed=1.0
